# Generated by Django 5.0 on 2023-12-21 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_number",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("course_name", models.CharField(max_length=40)),
                ("max_numb_students", models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "uid",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("r_number", models.CharField(max_length=6, unique=True)),
                ("seating_capacity", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ClassTime",
            fields=[
                ("pid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("9:30 - 10:30", "9:30 - 10:30"),
                            ("10:30 - 11:30", "10:30 - 11:30"),
                            ("11:30 - 12:30", "11:30 - 12:30"),
                            ("12:30 - 1:30", "12:30 - 1:30"),
                            ("2:30 - 3:30", "2:30 - 3:30"),
                            ("3:30 - 4:30", "3:30 - 4:30"),
                            ("4:30 - 5:30", "4:30 - 5:30"),
                        ],
                        default="11:30 - 12:30",
                        max_length=50,
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                        ],
                        max_length=15,
                    ),
                ),
                ("duration", models.IntegerField(default=60)),
            ],
            options={
                "unique_together": {("time", "day")},
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dept_name", models.CharField(max_length=50)),
                ("courses", models.ManyToManyField(to="timetables.course")),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="professor",
            field=models.ManyToManyField(to="timetables.professor"),
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "section_id",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("num_class_in_week", models.IntegerField(default=0)),
                (
                    "class_time",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetables.classtime",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetables.course",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetables.department",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetables.professor",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetables.room",
                    ),
                ),
            ],
        ),
    ]
