# Generated by Django 5.0 on 2023-12-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetables", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classtime",
            name="pid",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
