# Generated by Django 5.0 on 2023-12-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timetables", "0002_alter_classtime_pid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="professor",
            new_name="professors",
        ),
    ]
